---
###################################
# Pre-req
###################################
- name: 'Check minikube Pre-req'
  include_tasks: minikube_pre_reqs.yml

###################################
# Create
###################################
- name: 'Create minikube Cluster(s)'
  include_tasks: minikube_create.yml

###################################
# Destroy
###################################
- name: 'Destroy minikube Cluster(s)'
  include_tasks: minikube_destroy.yml
