---
- name: "Check if {{minikube_profile_name}} already exists"
  command:
    argv:
      - "{{minikube_binary}}"
      - "profile"
      - "list"
  register: profile_check_result
  changed_when: False

- set_fact: 
    profile_name: '{{ profile_check_result.stdout_lines | join("~") | regex_search(minikube_profile_name)}}'

#- debug: msg="{{profile_check_result}}" 

- name: "Create minikube profile {{minikube_profile_name}}"
  command:
      argv:
        - "{{minikube_binary}}"
        - -p
        - "{{minikube_profile_name}}"
        - start
        - --memory={{minikube_memory}}
        - --cpus={{minikube_cpus}}
        - --disk-size={{minikube_disk_size}}
        - --delete-on-failure=true
        - --driver={{minikube_driver}}
  register: minikube_start_result
  when: profile_name | length == 0

# - debug: msg="{{minikube_start_result}}"

- name: "Fail when not started"
  fail:
   msg: "Unable to start minikube"
  when: minikube_start_result.rc is defined and minikube_start_result.rc != 0

- name: "Set profile as current profile"
  command:
     argv:
       - "{{minikube_binary}}"
       - profile
       - "{{minikube_profile_name}}"
  changed_when: False
  
- name: "Enabling addon"
  command:
     argv:
       - "{{minikube_binary}}"
       - addons
       - enable
       - "{{item}}"
  loop: "{{minikube_addons}}"
  register: addons_enable_result
  changed_when: False
