---
- name: Converge
  hosts: localhost
  connection: local


  vars:
   ansible_python_interpreter: '{{ ansible_playbook_python }}'
   minikube_profile_name: molecule

  roles:
    - role: kameshsampath.minikube
