name: Site

on:
  push:
    branches:
      - "main"
env:
  SITE_DIR: "site"

jobs:
  buildAnDeploySite:
    name: "Build site with mkdocs"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: 
        - 3.10.0
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Build Site
        run: |
           mkdocs build
      - name: Deploy Site
        id: deploy_site
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: "${{ env.SITE_DIR }}"
          publish_branch: "gh-pages"          
          full_commit_message: "[Release]${{ github.event.head_commit.message }}"
